apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${app_name}
  namespace: demo-namespace
spec:
  replicas: ${replicas}
  selector:
    matchLabels:
      app: ${app_name}
  template:
    metadata:
      labels:
        app: ${app_name}
    spec:
      containers:
      - name: ${app_name}
        image: ${app_image}
        ports:
        - containerPort: ${app_port}
