apiVersion: v1
kind: Service
metadata:
  name: ${app_name}-service
  namespace: demo-namespace
spec:
  selector:
    app: ${app_name}
  ports:
    - protocol: TCP
      port: ${app_port}
      targetPort: ${app_port}
  type: LoadBalancer
